In [1]:
import torch

x = torch.arange(16)
print(x)
print(x.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
torch.Size([16])


In [2]:
reshaped_x = x.reshape(4, 4)
print(reshaped_x)
print(reshaped_x.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
torch.Size([4, 4])


In [3]:
tensor = torch.tensor([[[1,2,3,4]]])
print(tensor)
print(tensor.shape)

tensor([[[1, 2, 3, 4]]])
torch.Size([1, 1, 4])


In [5]:
squeezed_tensor = tensor.squeeze()
print(squeezed_tensor)
print(squeezed_tensor.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [7]:
squeezed_dim_tensor = tensor.squeeze(0)
print(squeezed_dim_tensor)
print(squeezed_dim_tensor.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
