In [2]:
import torch
import torch.nn as nn

linear_layer = nn.Linear(in_features=10, out_features=1)


sigmoid

In [3]:
input_tensor = torch.randn(1, 10)
print("Input Tensor:\n", input_tensor)


Input Tensor:
 tensor([[ 0.3466, -0.6505, -0.0334, -0.2680,  1.3698,  2.3642, -1.2011, -0.2752,
          0.3094,  1.2061]])


In [4]:
linear_output = linear_layer(input_tensor)
print(linear_output)

tensor([[0.8357]], grad_fn=<AddmmBackward0>)


In [5]:
sigmoid_output = torch.sigmoid(linear_output)
print(sigmoid_output)

tensor([[0.6976]], grad_fn=<SigmoidBackward0>)


tanh

In [7]:
linear_layer = nn.Linear(in_features=10, out_features=1)


In [8]:
input_tensor = torch.randn(1, 10)
print(input_tensor)

tensor([[ 0.7601,  0.4075,  1.7649, -0.7595, -0.9482,  0.2310, -1.5496, -0.4046,
          1.4220,  0.3776]])


In [10]:
linear_output = linear_layer(input_tensor)
print(linear_output)

tensor([[0.3912]], grad_fn=<AddmmBackward0>)


In [12]:
sigmoid_output = torch.sigmoid(linear_output)
print(sigmoid_output)

tensor([[0.5966]], grad_fn=<SigmoidBackward0>)


tanh

In [21]:
linear_layer = nn.Linear(in_features=10, out_features=1)

In [22]:
input_tensor = torch.randn(1, 10)
print(input_tensor)

tensor([[ 0.4176,  1.5880, -0.9254, -0.4300,  1.6782, -0.1599, -1.2125,  0.6901,
          0.2297, -0.1809]])


In [18]:
linear_output = linear_layer(input_tensor)
print(linear_output)

tensor([[-0.5331]], grad_fn=<AddmmBackward0>)


In [20]:
tanh_output = torch.tanh(linear_output)
print(tanh_output)

tensor([[-0.4878]], grad_fn=<TanhBackward0>)


Relu

In [25]:
linear_layer = nn.Linear(in_features=10, out_features=1)
print(linear_layer)

Linear(in_features=10, out_features=1, bias=True)


In [26]:
relu_layer = nn.ReLU()

In [27]:
input_tensor = torch.randn(1,10)
print(input_tensor)

tensor([[-1.5069,  0.1984,  0.3689,  0.4565,  1.6798,  0.6511,  0.0786,  0.9551,
         -0.6630, -1.8009]])


In [28]:
linear_output = linear_layer(input_tensor)
print(linear_output)

tensor([[-0.5559]], grad_fn=<AddmmBackward0>)


In [29]:
relu_output = nn.ReLU(linear_output)
print(relu_output)

ReLU(inplace=True)


Leaky ReLU

In [30]:
linear_layer = nn.Linear(in_features=10, out_features=1)
print(linear_layer)

Linear(in_features=10, out_features=1, bias=True)


In [32]:
leaky_relu = nn.LeakyReLU(negative_slope = 0.01)
print(leaky_relu)

LeakyReLU(negative_slope=0.01)


In [33]:
input_tensor = torch.randn(1, 10)
print(input_tensor)

tensor([[-0.9952,  0.7417,  1.7884, -0.4704,  2.0833, -0.6096,  1.0633,  1.1726,
         -1.0267,  0.1462]])


In [35]:
linear_output = linear_layer(input_tensor)
print(linear_output)

tensor([[-0.3953]], grad_fn=<AddmmBackward0>)


In [36]:
leaky_relu_output = leaky_relu(linear_output)
print(leaky_relu_output)

tensor([[-0.0040]], grad_fn=<LeakyReluBackward0>)


softmax

In [38]:
linear_layer = nn.Linear(in_features=10, out_features=1)

softmax = nn.Softmax(dim=1)

In [39]:
input_tensor = torch.randn(1,10)
print(input_tensor)

tensor([[-3.2761, -0.9107, -1.9335,  1.0555,  0.2289, -1.2899,  1.7663, -0.2937,
          1.2752, -0.5714]])


In [40]:
linear_output = linear_layer(input_tensor)
print(linear_output)

tensor([[0.0266]], grad_fn=<AddmmBackward0>)


In [41]:
softmax_output = softmax(linear_output)
print(softmax_output)

tensor([[1.]], grad_fn=<SoftmaxBackward0>)


dropout

In [42]:
dropout = nn.Dropout(p=0.5)

input_data = torch.randn(1, 10)

output = dropout(input_data)

print(input_data)

tensor([[ 0.7614, -0.0614, -0.0229, -1.1953,  0.9656,  1.6679, -0.6855,  1.8620,
          0.3217, -0.6839]])


In [43]:
print(output)

tensor([[ 0.0000, -0.1229, -0.0458, -0.0000,  0.0000,  3.3358, -1.3710,  3.7241,
          0.6433, -1.3678]])


Sequential을 사용하여 신경망 모델 만들기

In [44]:
model = nn.Sequential(
    nn.Linear(784, 256),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(256, 128),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(128, 10)
)

print(model)

Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=256, out_features=128, bias=True)
  (4): ReLU()
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=128, out_features=10, bias=True)
)


Module 상속 클래스로 모델 만들기

In [45]:
class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()

        self.fc1 = nn.Linear(784, 128)
        self.relu1 = nn.ReLU()

        self.fc2 = nn.Linear(128, 64)
        self.relu2 = nn.ReLU()

        self.fc3 = nn.Linear(64, 10)

        self.dropout = nn.Dropout(0.2)

def forward(self, x):
    x = self.relu1

    x = self.dropout

    x = self.relu2(self.fc2(x))

    x = self.fc3(x)

    return nn.Softmax(dim=1)(x)

model = CustomModel()
model


CustomModel(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=64, out_features=10, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)