In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [3]:
# nn.Linear

input_data = torch.rand(1, 5)

fc_layer = nn.Linear(in_features=5, out_features=3)



output = fc_layer(input_data)

print(fc_layer)
print(input_data)
print(output)

Linear(in_features=5, out_features=3, bias=True)
tensor([[0.5340, 0.3655, 0.7679, 0.1413, 0.3682]])
tensor([[-0.2945,  0.0860, -0.0413]], grad_fn=<AddmmBackward0>)


In [4]:
# torch.nn.functional
input_data = torch.rand(1, 5)

# 출력 차원:3 , 입력 차원:5
weight = torch.rand(3, 5)

# 출력 차원에 해당하는 바이어스
bias = torch.rand(3)



output = F.linear(input_data, weight, bias)

print(weight)
print(bias)
print(input_data)
print(output)


tensor([[0.0243, 0.4807, 0.1886, 0.2979, 0.0842],
        [0.7172, 0.1929, 0.3372, 0.3018, 0.3463],
        [0.6583, 0.7525, 0.5474, 0.1512, 0.8719]])
tensor([0.2269, 0.8367, 0.8542])
tensor([[0.5701, 0.9126, 0.3374, 0.8302, 0.6995]])
tensor([[1.0494, 2.0282, 2.8364]])


In [6]:
# torch.nn.functional

# 배치크기 1, 채널1, 높이5, 너비5
input_data = torch.rand(1, 1, 5, 5)

weight = torch.rand(1,1,3,3)
# 선택적으로 바이어스 정의 : 출력 채널 1에 대한 바이어스
bias = torch.rand(1)

# F.conv2d 함수를 사용하여 2D 컨볼루션 수행
output = F.conv2d(input_data, weight, bias, stride=1, padding=1)
print(output)

tensor([[[[2.5462, 2.8484, 2.5715, 1.9631, 1.4381],
          [2.6771, 3.7383, 3.4687, 2.5146, 1.3661],
          [3.0347, 4.0338, 3.2022, 2.9438, 1.6967],
          [3.4024, 4.3815, 3.6829, 3.4091, 1.9058],
          [2.8441, 3.6934, 3.4873, 2.6722, 2.0063]]]])


In [7]:
input_data = torch.tensor([-1.0, -0.5, 0.0, 0.5, 1.0])
print(input_data)

tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000])


In [9]:
output = F.relu(input_data)
print(output)

tensor([0.0000, 0.0000, 0.0000, 0.5000, 1.0000])


In [10]:
# input_data에 dropout함수 적용하기

input_tensor = torch.randn(3,3)
print(input_tensor)

tensor([[ 0.2792, -1.8443,  0.6378],
        [ 1.4860, -0.6832,  1.3859],
        [-0.0657,  1.3301, -1.4027]])


In [12]:
output1 = F.dropout(input_tensor, p=0.5, training=True)
print(output1)

tensor([[ 0.5585, -3.6887,  0.0000],
        [ 0.0000, -1.3664,  2.7718],
        [-0.0000,  0.0000, -2.8053]])


In [13]:
output2 = F.dropout(input_tensor, p=0.5, training=False)
print(output2)

tensor([[ 0.2792, -1.8443,  0.6378],
        [ 1.4860, -0.6832,  1.3859],
        [-0.0657,  1.3301, -1.4027]])


nn.Parameter를 이용해 F.linear에서 사용할 파라미터 정의해보기 <p>
weight, bias 정의하기 <p>
parameters()함수를 이용해 모델에 파라미터가 잘 정의되어 있는지 확인하기

In [14]:
class SimpleLinearModel(nn.Module):
    def __init__(self, input_size, output_size):
        super(SimpleLinearModel, self).__init__()

        self.weight = nn.Parameter(torch.randn(output_size, input_size))
        self.bias = nn.Parameter(torch.randn(output_size))

    def forward(self, x):
        return F.linear(x, self.weight, self.bias)
    
model = SimpleLinearModel(input_size=10, output_size=2)

print('매개변수이름과 크기 확인')
for name, param in model.named_parameters():
    print(f'{name}: {param.size()}')

매개변수이름과 크기 확인
weight: torch.Size([2, 10])
bias: torch.Size([2])


In [15]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.7003, -2.2449,  1.1661,  0.9697,  1.0823, -1.2409,  0.6391, -0.8863,
          1.5733,  0.1406],
        [-1.6831, -2.1309, -0.1386, -0.1918,  0.0901,  0.2835, -1.6413,  0.8510,
          1.1300, -0.0571]], requires_grad=True)
Parameter containing:
tensor([ 0.1348, -0.8517], requires_grad=True)


PyTorch를 사용하여 SimpleNeuralNetwork 신경망모델 구현
모델은 nn.Module을 상속받아야 합니다.
모델은 입력층, 하나의 은닉층, 그리고 출력층을 포함해야 합니다.
은닉층과 출력층 사이에는 드롭아웃을 적용해야 합니다. 드롭아웃 비율은 0.5로 설정하세요.
은닉층의 활성화 함수로는 ReLU를 사용해야 합니다.
init 메소드 내에서 은닉층과 출력층의 가중치 및 바이어스를 nn.Parameter를 사용하여 정의해야 합니다.
모델은 입력 크기가 10, 은닉층 크기가 5, 출력 크기가 2인 구조를 가져야 합니다.
forward 메소드를 구현하여 데이터가 모델을 통과하는 방식을 정의해야 합니다.
forward 메소드 내에서는 nn.functional.linear을 사용하여 선형 변환을 수행하고, nn.functional.dropout을 사용하여 드롭아웃을 적용해야 합니다.

In [16]:
class SimpleNeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, dropout_rate=0.5):
        super(SimpleNeuralNetwork, self).__init__()

        self.weight1 = nn.Parameter(torch.randn(hidden_size, input_size))
        self.bias1 = nn.Parameter(torch.randn(hidden_size))
        
        self.weight2 = nn.Parameter(torch.randn(output_size, hidden_size))
        self.bias2 = nn.Parameter(torch.randn(output_size))

        self.dropout_rate = dropout_rate

    def forward(self, x):
        x = F.relu(F.linear(x, self.weight1, self.bias))

        x = F.dropout(x, p=self.dropout_rate, training=self.training)

        x = F.linear(x, self.weight2, self.bias2)

        return x
    
model = SimpleNeuralNetwork(input_size=10, hidden_size=5, output_size=2, dropout_rate=0.5)
print(model)

SimpleNeuralNetwork()
