𝑦=𝑊𝑥+𝑏

In [1]:
import torch

def custom_layer(x, weight, bias):
    x = torch.matmul(weight, x) + bias
    return x


In [2]:
input_tensor = torch.randn(10, 1)

weight = torch.randn(2, 10)
bias = torch.randn(2)

output = custom_layer(input_tensor, weight, bias)
print(output)

tensor([[-0.5812, -0.6695],
        [ 1.8896,  1.8013]])


𝑦=𝑠𝑖𝑛(𝑥𝑊𝑇)+𝑏

In [3]:
def custom_sin_layer(x, weight, bias):
    x = torch.matmul(x, weight.t())
    x = torch.sin(x)
    return x

In [5]:
input_tensor = torch.randn(1, 10)

weight = torch.randn(2,10)
bias = torch.randn(1)

output = custom_sin_layer(input_tensor, weight, bias)
output

tensor([[-0.7258,  0.6141]])

클래스행 사용자 정의 연산


𝑌=𝑋𝑊𝑇+𝑏

In [6]:
import torch.nn as nn

class CustomLinearLayer(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(CustomLinearLayer, self).__init__()

        self.weight = nn.Parameter(torch.randn(output_dim, input_dim))
        self.bias = nn.Parameter(torch.randn(output_dim))

    def forward(self, x):
        y = torch.matmul(x, self.weight.t()) + self.bias
        return y

In [7]:
import torch.nn as nn

class CustomLinearLayer(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(CustomLinearLayer, self).__init__()

        self.weight = nn.Parameter(torch.randn(output_dim, input_dim))
        self.bias = nn.Parameter(torch.randn(output_dim))

    def forward(self, x):
        y = torch.matmul(x, self.weight.t()) + self.bias
        return y

In [8]:
input_dim = 5
output_dim = 3

custom_layer = CustomLinearLayer(input_dim, output_dim)

x = torch.randn(2, input_dim)

y = custom_layer(x)

print(y)

tensor([[ 0.9795,  0.9588, -2.0064],
        [ 1.4922, -1.4882, -4.8339]], grad_fn=<AddBackward0>)


CustomLinearLayer를 이용해 딥러닝 모델을 정의

In [9]:
import torch.nn.functional as F

class CustomMLP(nn.Module):
    def __init__(self):
        super(CustomMLP, self).__init__()
        self.fc1 = CustomLinearLayer(20, 50)
        self.fc2 = CustomLinearLayer(50,30)
        self.fc3 = CustomLinearLayer(30, 3)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [11]:
model = CustomMLP()

x = torch.randn(5, 20)

output = model(x)

print(output)

tensor([[ -10.9929,  116.3370,    4.0705],
        [-105.5011,  183.1091,  -78.2415],
        [-189.9433,  155.8652,   30.0282],
        [ -86.9582,  104.7683,  -36.5953],
        [-327.8688,  387.7746,  -62.6643]], grad_fn=<AddBackward0>)


In [12]:
output.size()

torch.Size([5, 3])